subscription_id         = "1b5b28ed-1365-4a48-b285-80f80a6aaa1b"
resource_group_name     = "rg-portal-sync-tf-dev-uksouth"
storage_account_name    = "saptlsynctfdev"
container_name          = "terraform"
key                     = "terraform.tfstate"