name: Destroy Development

on:
  workflow_dispatch:  
  schedule:
    - cron: "0 23 * * *"

permissions:
  id-token: write # This is required for Az CLI Login
  contents: read # This is required for actions/checkout

jobs:
  terraform-destroy-dev:
    environment: Development
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.repository }}-dev

    steps:
    - uses: actions/checkout@v4

    - uses: frasermolyneux/actions/terraform-destroy-resources@main
      with:
        terraform-folder: "terraform"
        terraform-var-file: "tfvars/dev.tfvars"
        terraform-backend-file: "backends/dev.backend.hcl"
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resources: "[\"azurerm_management_lock.rg_lock\",\"azurerm_management_lock.kv_lock\",\"azurerm_linux_function_app.app\"]"
